version: '3'
services:
  cache:
    networks:
      - pycache_kafka-net
    build:
      context: .
    volumes:
      - ./app:/www/app/app
    ports:
      - "8001:80"

networks:
  pycache_kafka-net:
    external: true